title: Erruan9921's blog
author: Erruan9921
email: erruan.g@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here is erruan's blog, hope you can enjoy your time.

# social links
twitter_username: erruan-twitter # DO NOT include the @ character, or else the build will fail!
github_username:  erruan-github # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
